### ISSUE TITLE
unite terminology: "Bookmarks" and "Query lists"

### ISSUE THREAD

**Issue by Ansa211** [ufal/perl-pmltq-web#93]
Even after hearing from Pavel about the new "Query lists" feature, it took me ages to find where I can create my own new list. It's a little confusing that it is hidden behind "Bookmarks" but everywhere else the word "Query list" or just "Queries" (as in "Public queries") is used.

Suggestions:
- rename the "Bookmarks" menu item to "My queries" or "Query lists"
- reorder the items in the menu: Query - My queries - Public queries - Help
- add a "New" button to the bottom of the "Query list:" menu that appears directly above the query when one is logged in
- the mouseover text on the "Query list:" button (which now simply repeats the name of the button: "Query lists:") should be more explanatory: "Use the "My queries" menu to organize and annotate your query lists"

**Comment by matyaskopp** [comment]
Thanks for suggestions

## TODO:

- [ ] "Bookmarks" -> "My queries"
- [ ] reorder menu
- [ ] "New" button to "Query list:" menu in "Query" tab
- [ ] mouseover text "Use the "My queries" menu to organize and annotate your query lists" on "Query lists"
